stars = ('*')*36
print(stars)
print()
print('My Coffee and Muffin Shop')
print()
coffee = int(input('Number of coffees bought?: '))
print()
muffin = int(input('Number of muffins bought?: '))
print()
latte = int(input('Number of lattes bought?: '))
print()
espresso = int(input('Number of espressos bought?: '))
print()
print(stars)
print()
print()
print(stars)
print()
print('My Coffee and Muffin shop receipts')
print(coffee, 'at 5 dollars each is:',coffee * 5)
print(muffin, 'at 4 dollars each is:',muffin * 4)
print(latte, 'at 7 dollars each is:',latte * 7)
print(espresso, 'at 3 dollars each is:',espresso * 3)
tax = .06*(coffee*5 + muffin*4 + lattes*7 + espresso*3)
print('6% tax is ',tax)
print('------------')
print('total is ',coffee*5 + muffin*5 + latte*7 + espresso*3 + tax)
print(stars)
